import { useState } from 'react';
import './Hero.css';

const EDITOR_TABS = {
  'about.js': <><span className="tok-key">const</span> <span className="tok-var">developer</span> = {'{'}<br />  name: <span className="tok-str">&quot;Vansh Bijwe&quot;</span>,<br />  role: <span className="tok-str">&quot;Frontend Developer&quot;</span>,<br />  location: <span className="tok-str">&quot;Amravati, India&quot;</span>,<br />  focus: <span className="tok-str">&quot;UI Engineering&quot;</span>,<br />  stack: [<span className="tok-str">&quot;HTML&quot;</span>, <span className="tok-str">&quot;CSS&quot;</span>,<br />          <span className="tok-str">&quot;JavaScript&quot;</span>, <span className="tok-str">&quot;React&quot;</span>],<br />  available: <span className="tok-bool">true</span><br />{'}'};</>,
  'skills.js': <><span className="tok-key">const</span> <span className="tok-var">toolkit</span> = {'{'}<br />  frontend: [<span className="tok-str">&quot;HTML5&quot;</span>, <span className="tok-str">&quot;CSS3&quot;</span>,<br />             <span className="tok-str">&quot;JavaScript&quot;</span>, <span className="tok-str">&quot;React&quot;</span>],<br />  tools: [<span className="tok-str">&quot;Git&quot;</span>, <span className="tok-str">&quot;Figma&quot;</span>, <span className="tok-str">&quot;REST APIs&quot;</span>],<br />  learning: [<span className="tok-str">&quot;Node.js&quot;</span>, <span className="tok-str">&quot;AI Integration&quot;</span>]<br />{'}'};</>,
  'projects.js': <><span className="tok-key">const</span> <span className="tok-var">selectedWork</span> = [<br />  {'{'} name: <span className="tok-str">&quot;Advocate Brief&quot;</span>, type: <span className="tok-str">&quot;Web App&quot;</span> {'}'},<br />  {'{'} name: <span className="tok-str">&quot;Campus Connect&quot;</span>, type: <span className="tok-str">&quot;Portal&quot;</span> {'}'}<br />];<br /><br /><span className="tok-comment">// Thoughtful interfaces, built to ship.</span></>,
};
function Hero() {
  const [activeTab, setActiveTab] = useState('about.js');
  return <section id="top" className="hero"><div className="container hero__inner"><div className="hero__copy"><p className="eyebrow">frontend developer · ui engineer · amravati, india</p><h1 className="hero__title">Vansh Bijwe<br /><span>builds digital</span><br />experiences.</h1><p className="hero__desc">I design and build fast, responsive and user-focused web experiences that turn ideas into products — with HTML, CSS, JavaScript, React, Bootstrap and REST APIs.</p><div className="hero__actions"><a href="#projects" className="btn btn-primary">view selected work <span>→</span></a><a href="#contact" className="btn btn-ghost">let&apos;s talk <span>↗</span></a></div><div className="availability"><span className="availability__dot" /><div><strong>available for work</strong><small>Frontend Development · React · UI Engineering</small></div></div></div><div className="hero__panel"><div className="floating-note"><span>✦ currently building</span><strong>React applications<br />&amp; AI-powered products</strong></div><div className="editor"><div className="editor__bar"><div className="editor__dots" aria-hidden="true"><span /><span /><span /></div><div className="editor__tabs" role="tablist" aria-label="Code editor tabs">{Object.keys(EDITOR_TABS).map((tab) => <button key={tab} role="tab" aria-selected={activeTab === tab} className={`editor__tab ${activeTab === tab ? 'editor__tab--active' : ''}`} onClick={() => setActiveTab(tab)}>{tab}</button>)}</div></div><div className="editor__body" key={activeTab}><pre><code>{EDITOR_TABS[activeTab]}<span className="editor__caret" /></code></pre></div><div className="editor__footer"><span>UTF-8</span><span>JavaScript</span><span className="editor__footer-live"><i /> ready</span></div></div></div></div></section>;
}
export default Hero;
